// backend/productsData.js
export const initialProducts = [
  {
    id: 1,
    name: "Cashmere Overcoat",
    description:
      "A luxurious cashmere overcoat tailored for effortless elegance. Features a relaxed silhouette with notched lapels and a single-breasted closure, perfect for layering over both formal and casual outfits during cooler months.",
    price: 289,
    originalPrice: 349,
    category: "Outerwear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#2d2d2d", "#8b7355", "#c4a882"],
    rating: 4.8,
    reviews: 124,
    badge: "Best Seller",
    image:
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 2,
    name: "Silk Midi Dress",
    description:
      "An effortlessly graceful silk midi dress with a fluid drape that moves beautifully with every step. The bias-cut silhouette flatters all body types, while delicate seam detailing adds subtle structure to this timeless piece.",
    price: 179,
    originalPrice: null,
    category: "Dresses",
    sizes: ["XS", "S", "M", "L"],
    colors: ["#1a1a2e", "#e8d5c4", "#6b4226"],
    rating: 4.9,
    reviews: 89,
    badge: "New",
    image:
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 3,
    name: "Tailored Wool Blazer",
    description:
      "A impeccably tailored wool blazer crafted from premium Italian wool blend fabric. The structured shoulders and slim-fit cut create a polished silhouette, making it an essential piece for the modern wardrobe.",
    price: 229,
    originalPrice: 279,
    category: "Outerwear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#1a1a1a", "#4a4a4a", "#8b7355"],
    rating: 4.7,
    reviews: 201,
    badge: "Sale",
    image:
      "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 4,
    name: "Organic Cotton Tee",
    description:
      "A buttery-soft organic cotton tee that delivers all-day comfort without compromising on style. The relaxed fit and reinforced seams ensure durability, while the sustainable fabric feels gentle against the skin.",
    price: 49,
    originalPrice: null,
    category: "Tops",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["#ffffff", "#1a1a1a", "#97c1a9", "#d4a574"],
    rating: 4.6,
    reviews: 342,
    badge: null,
    image:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 5,
    name: "High-Rise Wide Leg Pants",
    description:
      "Statement wide-leg pants with a flattering high-rise waistline that elongates the legs. The flowing silhouette and pressed front crease lend a refined edge, while the lightweight fabric keeps you comfortable from day to night.",
    price: 119,
    originalPrice: 149,
    category: "Bottoms",
    sizes: ["XS", "S", "M", "L"],
    colors: ["#1a1a1a", "#f5f5dc", "#4a4a4a"],
    rating: 4.5,
    reviews: 167,
    badge: "Sale",
    image:
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 6,
    name: "Linen Summer Dress",
    description:
      "A breezy linen summer dress designed for warm-weather elegance. The breathable fabric and relaxed A-line cut keep you cool, while the subtle texture and soft palette make it ideal for beach getaways and garden parties alike.",
    price: 159,
    originalPrice: null,
    category: "Dresses",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["#f5e6d3", "#bcd4e6", "#fadadd"],
    rating: 4.8,
    reviews: 93,
    badge: "New",
    image:
      "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 7,
    name: "Merino Wool Sweater",
    description:
      "A cozy merino wool sweater with a relaxed crew-neck fit that delivers warmth without bulk. The fine-gauge knit provides a smooth hand feel, while natural temperature regulation makes it perfect for layering in any season.",
    price: 139,
    originalPrice: null,
    category: "Tops",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#f5f5dc", "#8b4513", "#2f4f4f"],
    rating: 4.7,
    reviews: 215,
    badge: null,
    image:
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 8,
    name: "Pleated Midi Skirt",
    description:
      "A sophisticated pleated midi skirt that adds instant polish to any outfit. The accordion pleats create beautiful movement, while the elasticized waistband ensures a comfortable, flattering fit throughout the day.",
    price: 99,
    originalPrice: 129,
    category: "Bottoms",
    sizes: ["XS", "S", "M", "L"],
    colors: ["#1a1a1a", "#d4a574", "#6b4226"],
    rating: 4.4,
    reviews: 78,
    badge: "Sale",
    image:
      "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 9,
    name: "Denim Jacket Classic",
    description:
      "A timeless denim jacket built from premium heavyweight cotton with a lived-in wash. The classic trucker silhouette features button-flap chest pockets and adjustable waist tabs, delivering authentic Americana style that only gets better with age.",
    price: 169,
    originalPrice: null,
    category: "Outerwear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#4169e1", "#1a1a1a", "#f5f5dc"],
    rating: 4.6,
    reviews: 256,
    badge: "Best Seller",
    image:
      "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 10,
    name: "Relaxed Linen Shirt",
    description:
      "A relaxed-fit linen shirt that embodies effortless sophistication. The garment-washed fabric offers a soft, broken-in feel from the first wear, while the camp collar and curved hem give it a laid-back Mediterranean vibe.",
    price: 89,
    originalPrice: null,
    category: "Tops",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#ffffff", "#bcd4e6", "#f5e6d3"],
    rating: 4.5,
    reviews: 134,
    badge: null,
    image:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 11,
    name: "Velvet Evening Gown",
    description:
      "A show-stopping velvet evening gown with a figure-skimming silhouette that exudes glamour. The sumptuous velvet fabric catches the light beautifully, while the subtle V-neckline and open back add modern allure to a classic design.",
    price: 349,
    originalPrice: 429,
    category: "Dresses",
    sizes: ["XS", "S", "M", "L"],
    colors: ["#800020", "#1a1a2e", "#2f4f4f"],
    rating: 4.9,
    reviews: 47,
    badge: "Premium",
    image:
      "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 12,
    name: "Stretch Slim Jeans",
    description:
      "Precision-engineered slim jeans with a hint of stretch for unrestricted movement. The tapered leg creates a sleek profile, while the mid-rise waist and five-pocket styling deliver everyday versatility without sacrificing comfort.",
    price: 109,
    originalPrice: null,
    category: "Bottoms",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["#1a1a2e", "#4a4a4a", "#1a1a1a"],
    rating: 4.6,
    reviews: 389,
    badge: "Best Seller",
    image:
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 13,
    name: "Satin Wrap Blouse",
    description:
      "A lustrous satin wrap blouse with a flattering V-neckline and adjustable tie closure. The fluid fabric drapes elegantly across the body, making it a versatile piece that transitions seamlessly from office hours to evening outings.",
    price: 98,
    originalPrice: 120,
    category: "Tops",
    sizes: ["XS", "S", "M", "L"],
    colors: ["#e8d5c4", "#1a1a2e", "#800020"],
    rating: 4.7,
    reviews: 64,
    badge: "Sale",
    image:
      "https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 14,
    name: "Classic Trench Coat",
    description:
      "An iconic trench coat reimagined with modern proportions and water-resistant gabardine fabric. The double-breasted front, storm flap, and belted waist create a structured silhouette that has remained a style staple for decades.",
    price: 249,
    originalPrice: null,
    category: "Outerwear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#c4a882", "#1a1a1a"],
    rating: 4.8,
    reviews: 112,
    badge: "Best Seller",
    image:
      "https://images.unsplash.com/photo-1544441893-675973e31985?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 15,
    name: "Tailored Ankle Trousers",
    description:
      "Crisply tailored ankle-length trousers with a slim fit that hits at the perfect spot above the shoe. The flat-front design and pressed crease deliver a sharp, tailored look, while the hidden elastic waistband adds unexpected comfort.",
    price: 129,
    originalPrice: null,
    category: "Bottoms",
    sizes: ["XS", "S", "M", "L"],
    colors: ["#1a1a1a", "#2d2d2d", "#8b7355"],
    rating: 4.5,
    reviews: 95,
    badge: "New",
    image:
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 16,
    name: "Floral Slip Dress",
    description:
      "A delicate floral slip dress with abias-cut hem that skims the body beautifully. The adjustable spaghetti straps and lightweight chiffon fabric make it perfect for layering over a tee or wearing solo on warm evenings.",
    price: 145,
    originalPrice: 175,
    category: "Dresses",
    sizes: ["XS", "S", "M", "L"],
    colors: ["#fadadd", "#1a1a2e"],
    rating: 4.6,
    reviews: 81,
    badge: "Sale",
    image:
      "https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 17,
    name: "Chunky Knit Cardigan",
    description:
      "A plush chunky knit cardigan with an oversized fit that wraps you in warmth. The ribbed cuffs and hem add texture, while the front patch pockets provide a cozy place to rest your hands on chilly days.",
    price: 115,
    originalPrice: null,
    category: "Tops",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#f5f5dc", "#8b7355", "#97c1a9"],
    rating: 4.8,
    reviews: 142,
    badge: "New",
    image:
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 18,
    name: "Leather Biker Jacket",
    description:
      "A premium leather biker jacket crafted from full-grain lambskin that develops a rich patina over time. The asymmetric zip closure, quilted shoulder panels, and snap-down collar deliver authentic motorcycle-inspired style.",
    price: 320,
    originalPrice: 380,
    category: "Outerwear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#1a1a1a", "#6b4226"],
    rating: 4.9,
    reviews: 158,
    badge: "Premium",
    image:
      "https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 19,
    name: "Ribbed Tank Top",
    description:
      "A versatile ribbed tank top made from stretch cotton that hugs the body for a sleek, form-fitting look. The scoop neckline and racerback design make it ideal for layering under blazers or wearing on its own during warmer weather.",
    price: 39,
    originalPrice: null,
    category: "Tops",
    sizes: ["XS", "S", "M", "L"],
    colors: ["#ffffff", "#1a1a1a", "#c4a882"],
    rating: 4.4,
    reviews: 118,
    badge: null,
    image:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 20,
    name: "A-Line Denim Skirt",
    description:
      "A classic A-line denim skirt with a flattering flared silhouette that suits every body type. The medium wash and raw hem give it a casual, lived-in feel, while the back slit ensures easy movement throughout the day.",
    price: 85,
    originalPrice: 110,
    category: "Bottoms",
    sizes: ["XS", "S", "M", "L"],
    colors: ["#4169e1", "#1a1a2e"],
    rating: 4.5,
    reviews: 67,
    badge: "Sale",
    image:
      "https://images.unsplash.com/photo-1582142307848-f60be5e38686?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 21,
    name: "Boho Maxi Dress",
    description:
      "A free-spirited boho maxi dress adorned with a hand-inspired print and tiered skirt. The smocked elastic waist creates a flattering shape, while the flutter sleeves and maxi length bring romantic, festival-ready charm.",
    price: 165,
    originalPrice: null,
    category: "Dresses",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["#e8d5c4", "#97c1a9", "#fadadd"],
    rating: 4.7,
    reviews: 104,
    badge: "New",
    image:
      "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 22,
    name: "Quilted Puffer Coat",
    description:
      "A lightweight quilted puffer coat insulated with responsibly sourced down for exceptional warmth without the weight. The stand collar and elasticated cuffs lock in heat, while the packable design makes it a travel essential.",
    price: 210,
    originalPrice: 260,
    category: "Outerwear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#1a1a1a", "#2f4f4f", "#f5f5dc"],
    rating: 4.8,
    reviews: 189,
    badge: "Sale",
    image:
      "https://images.unsplash.com/photo-1548883354-7622d03aca27?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 23,
    name: "Oversized Graphic Hoodie",
    description:
      "An oversized graphic hoodie made from heavy-duty French terry cotton for a premium, substantial feel. The dropped shoulders and kangaroo pocket deliver laid-back streetwear vibes, while the bold graphic print makes a statement.",
    price: 79,
    originalPrice: null,
    category: "Tops",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#4a4a4a", "#1a1a1a", "#f5f5dc"],
    rating: 4.6,
    reviews: 230,
    badge: "Best Seller",
    image:
      "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&h=800&fit=crop&q=80",
  },
  {
    id: 24,
    name: "Cargo Jogger Pants",
    description:
      "Functional cargo joggers that blend utility with modern comfort. The elastic waistband and cuffed ankles create a tapered silhouette, while multiple pockets provide practical storage for an on-the-go lifestyle.",
    price: 95,
    originalPrice: null,
    category: "Bottoms",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["#2f4f4f", "#1a1a1a", "#8b7355"],
    rating: 4.3,
    reviews: 72,
    badge: null,
    image:
      "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=600&h=800&fit=crop&q=80",
  },
];
